version: "3"

services:
  mariadb:
    image: mariadb
    container_name: users_mariadb
    restart: on-failure
    volumes:
      - ../infra/mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ilovedocker
    
  app:
    build: 
      context: .
    volumes: 
      - ./:/go/src/github.com/rampo0/multi-lang-microservice/users
    image: rampooco/users
    container_name: multi-users
    restart: on-failure
    ports:
      - 8080:8080
    depends_on: 
      - mariadb

  adminer:
    image: adminer
    container_name: users_adminer
    ports: 
      - "4001:8080"
    depends_on: 
      - mariadb
